/// Note that assertions inform typescript, but don't apply in prodction.
/// These can be treated as "informing typescript while also checking for obvious bugs at runtime"
/// and *NOT* as intended runtime logic. If it can be generated by passing a non-malicious value to the api,
/// it should be a regular check+throw, not an assertion
// Assertions are expensive, so we use them in development only - () => {} does not impact performance nearly as heavily
const assert: ((value: unknown, message?: string | Error) => asserts value) = (() => {
    return process?.env?.NODE_ENV === 'development' ? require('assert') : () => {};
})();

export default assert;
